spring:
  output:
    ansi:
      enabled: always
  application:
    name: history
  elasticsearch:
    uris: localhost:9200
server:
  shutdown: graceful
  port: 8081
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
logging:
  level:
    dev.fastcampus: debug
    org.springframework.r2dbc.core: debug
    org.springframework.r2dbc.connection.init: debug
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    org.springframework.web.HttpLogging: off
#    tracer: trace
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"