version: '3.8'
services:
  es:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    build:
        context: .
        args:
          ES_VERSION: 7.15.2
    container_name: es
    restart: unless-stopped
    ports:
      - 9200:9200 # client와 통신
      - 9300:9300 # ES cluster 간 통신
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - logger.level=ERROR
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - es-bridge
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ## depends on container name of elasticsearch
      ELASTICSEARCH_HOSTS: http://es:9200
    restart: unless-stopped      
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge
networks:
  es-bridge:
    driver: bridge