spring:
  application:
    name: spring-elasticsearch
  output:
    ansi:
      enabled: always
  elasticsearch:
    uris: localhost:9200
logging:
  level:
    dev.fastcampus: debug
#    org.springframework.data.elasticsearch: trace
#    org.springframework.data.elasticsearch.client.WIRE: trace
#    org.elasticsearch.client.RequestLogger: trace
    tracer: trace
#    root: trace
  pattern:
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"
#    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"

