spring:
  application:
    name: spring-coroutine-advanced
  output:
    ansi:
      enabled: always
  r2dbc:
    url: r2dbc:pool:mariadb://localhost:3306/sample
    username: user
    password: 1234
#    url: r2dbc:pool:h2:mem://localhost/test
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/test.sql
  data:
    redis:
      host: localhost
      port: 6379
server:
  shutdown: graceful
  compression:
    enabled: true
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: on_param
resilience4j:
  circuitbreaker:
    instances:
      sample:
        sliding-window-size: 10
        failure-rate-threshold: 20
        ## - close : 정상 (회로가 닫혀있다.)
        ## - open  : 오류 (회로가 열려있다.)
        ## - half-open : 반열림
        ## 반열림 진입시간
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
logging:
  level:
    org.springframework.r2dbc.core: debug
#    org.mariadb.r2dbc: trace
#    org.springframework.r2dbc.connection.init.ScriptUtils: debug

    ## AbstractErrorWebExceptionHandler 로깅 끄기
    org.springframework.web.HttpLogging: off
    org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler: off
    dev.fastcampus: debug
#    root: debug
  pattern:
    #    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    #    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%green(%t)] %blue(%50(\\(%F:%L\\))) %msg%n"
#    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid}|%green(%18.18t)|%blue(%50(\\(%F:%L\\)))|%msg%n"
#    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%blue(\\(%F:%L\\))|%msg%n"
    console: "%d{HH:mm:ss.SSS}|%highlight(%-5level)|%X{txid:-}|%green(%t)|%logger|%blue(\\(%F:%L\\))|%msg%n"
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true